### ISSUE TITLE
PSReadLine conflict with inshellisense

### ISSUE THREAD

**Issue by doggy8088** [microsoft/inshellisense#109]
**Describe the bug**

The PSReadLine contains command history listing feature. This feature seems conflict with inshellisense. I don't know how this can be fixed.

**To Reproduce**
1. Type `inshellisense --shell pwsh` and hit Enter

2. Type `git`, then it will show my previous command `git reset --soft HEAD~`.

    ![image](https://github.com/microsoft/inshellisense/assets/88981/ebdfa591-22c3-4b75-a693-ff7da49680ab)

3. I have a workaround that is type 3 spaces.

    ![image](https://github.com/microsoft/inshellisense/assets/88981/3efd8e4d-82d8-4cf2-99e1-d4abe9002f63)

**Expected behavior**

I expected to show inshellisense no matter how PSReadLine does.

**Environment**
 - OS: `Microsoft Windows [Version 10.0.19045.3693]`
 - Output of `inshellisense --version`: `0.0.1-rc.5`
 - Nodejs Version: `18.16.0`

**Additional context**
N/A

**Comment by cpendery** [comment]
@doggy8088 which version of `pwsh` are you using?

**Comment by cpendery** [comment]
I'm not able to replicate this issue at this point. If you build from source via the following commands and the logs at `~/.inshellisense/inshellisense.log` would be helpful for debugging.

```shell
git clone https://github.com/microsoft/inshellisense.git
cd inshellisense
npm install
npm run build && npm link
is -s pwsh -V # this will start inshellisense with verbose logs on, follow the setups above and then exit 
```

I'm going to close this until I have those logs.
