### ISSUE TITLE
PowerShell: The 'cd' command does not change directory

### ISSUE THREAD

**Issue by philibertperusse** [microsoft/inshellisense#11]
When running inshellisence, doing a 'cd [a_folder]' will not change directory properly even if folder exist.

And using the 'cd' suggestions of "../" will not work either

1. start inshellisense (manually or through the binding)
2. pwd
3. cd ..
4. pwd
6. Directory is the same, should not.

**Comment by lafonj** [comment]
This also happens in Linux

**Comment by josharian** [comment]
..and zsh on macOS.

**Comment by cpendery** [comment]
I think this is a duplicate of #5. I'm working on addressing this issue as I mentioned in #10. Thanks for reporting these!

**Comment by cpendery** [comment]
Closing as this was fixed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)
