### ISSUE TITLE
The xonsh shell support

### ISSUE THREAD

**Issue by anki-code** [microsoft/inshellisense#112]
Hi! Thank you for this great thing!
It will be cool to have the [xonsh shell](https://github.com/xonsh/xonsh) support.
Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by dedguy21** [comment]
That would be awesome, love Xonsh.

**Comment by cpendery** [comment]
@dedguy21 & @anki-code finished adding the xonsh support. I'm going to tweak the configuration and documentation before I cut the next release, but keep your eyes out for it

**Comment by cpendery** [comment]
Released!
