### ISSUE TITLE
Powershell: 'cd' does not show proper file suggestions

### ISSUE THREAD

**Issue by philibertperusse** [microsoft/inshellisense#12]
Using Powershell, when trying to change directory using 'cd', it only shows the following suggestions:
   ../
   -
   ~
Instead of showing all folders available.

However, when using a 'git add' command, it will show all files in current directory.

**Comment by gluons** [comment]
I still face this problem in the latest version.

![ภาพ](https://github.com/user-attachments/assets/6a3b468f-0b51-44db-98ca-650305ac1080)

**Comment by niikoo** [comment]
This is happening to me as well. On the last version.
