### ISSUE TITLE
Provide intenllisense for possible arguments. 

### ISSUE THREAD

**Issue by zhaowenquan131** [microsoft/inshellisense#127]
**Maybe it should be able to do something like**
e.g. list all local branches when I type "git checkout" in bash in a repository folder

**Comment by cpendery** [comment]
This should be working, but the generator is failing for the script `["git","--no-optional-locks","branch","-a","--no-color","--sort=-committerdate"]`. I'll look into it

**Comment by joaogsleite** [comment]
**The same with npm scripts:**
e.g. list all available scripts when I type "npm run" in a bash in a folder with a package.json file
