### ISSUE TITLE
Installation of rc5 or update to rc5 fails due to missing dependencies.

### ISSUE THREAD

**Issue by niStee** [microsoft/inshellisense#128]
**Describe the bug**
On my systems (amd64, win 10&11) the installation of rc5 requires node-gyp and its dependencies python and Visual Studio.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Windows PowerShell'
2. Enter on 'yarn add @microsoft/inshellisense@0.0.1-rc.5 -g'
4. See error.

**Expected behaviour**
Installation of Inshellisense does not require dependencies that are not automatically handled.

**Environment**
 — OS: [Windows 10 & Windows 11]
 — Output of `is --version`: [0.0.1-rc.5]
 — Node.js Version: [20.10.0]
 — Shell: [Microsoft.WindowsTerminal]
 — Shell Version: [1.18.3181.0]

**Comment by cpendery** [comment]
As with [node-pty](https://github.com/microsoft/node-pty?tab=readme-ov-file#dependencies) it is expected you handle your own dependencies. While some [prebuilds](https://github.com/homebridge/node-pty-prebuilt-multiarch) exist, which are used in [terminalizer](https://github.com/faressoft/terminalizer), I don't want to commit to using those at this point. I'd rather not pull in binary builds I don't control, but I'll revisit this in the future.

**Comment by niStee** [comment]
Just to get this straight:
python and c++ (via msvs) are dependencies to run is?

**Comment by cpendery** [comment]
@nistee, I'll be attempting to add binary builds you could install without npm that would include all the required dependencies, so that might fit your needs better in the future. You can follow #32
