### ISSUE TITLE
Can't I enter the breakpoint through IDE debugging?

### ISSUE THREAD

**Issue by alanhg** [microsoft/inshellisense#130]
**Is your feature request related to a problem? Please describe.**
It's better to inspect breakpoint on IDE

**Describe alternatives you've considered**
If not, I have to use log

**Comment by cpendery** [comment]
@alanhg, are you referring to debugging during the development of inshellisense?

**Comment by alanhg** [comment]
> @alanhg, are you referring to debugging during the development of inshellisense?

yes.I hope to debug in WebStorm, for example, and then enter the breakpoints marked in the code.

**Comment by cpendery** [comment]
Ah, I'm not sure how to debug in WebStorm, but if you run the npm command `npm run debug`, it will start up inshellisense with node's inspect enabled. In VSCode, you can attach to it via the `> Debug: Attach to Node Process` command. Then you can use breakpoints in the typescript code.

**Comment by alanhg** [comment]
> Ah, I'm not sure how to debug in WebStorm, but if you run the npm command `npm run debug`, it will start up inshellisense with node's inspect enabled. In VSCode, you can attach to it via the `> Debug: Attach to Node Process` command. Then you can use breakpoints in the typescript code.

debug is okay now in Visual Studio Code, thank you very much. As for WebStorm, I will study it further.

**Comment by alanhg** [comment]
> Ah, I'm not sure how to debug in WebStorm, but if you run the npm command `npm run debug`, it will start up inshellisense with node's inspect enabled. In VSCode, you can attach to it via the `> Debug: Attach to Node Process` command. Then you can use breakpoints in the typescript code.


1. remove inspect option
2. webstorm's debug click
3. it's ok to debug
<img width="1303" alt="image" src="https://github.com/microsoft/inshellisense/assets/9245110/78aa5598-c3af-4dd9-8bc5-11135fe9a35c">


I believe don't should to configure 'inspect' in the command script, We can operate directly in the IDE, or add a 'start' command. 

 "start": "node --loader ts-node/esm src/index.ts"
