### ISSUE TITLE
inshellisense dosen't work with PSReadLine?

### ISSUE THREAD

**Issue by wind-mask** [microsoft/inshellisense#140]
**Describe the bug**

In my pwsh inshellisense dosen't work and show.

**To Reproduce**

```shell
is -s 
pwsh -V 
``` 
Then I type git st..,no inshellisense . 
![t](https://github.com/microsoft/inshellisense/assets/110806349/e01e810a-b27a-4c14-a1f9-f003f1130fe8)

**Expected behavior** 

Show Completion.

**Environment** 

- OS: Windows11 23H2
- Output of `is --version`: 0.0.1-rc.6
- Nodejs Version: v20.10.0
- Shell: pwsh
- Shell Version: PowerShell 7.4.0

**Additional context** 

I used [starship](https://starship.rs/):starship 1.16.0

The log:
[inshellisense.log](https://github.com/microsoft/inshellisense/files/13766526/inshellisense.log)

**Comment by wind-mask** [comment]
Sorry,today i try to prohibit the use of starship,so we know this problem has nothing to do with starship.
![2023-12-27 12_14_52-Greenshot](https://github.com/microsoft/inshellisense/assets/110806349/0a761ae4-f1ac-43f6-b089-87c877430205)
The log:
[inshellisense.log](https://github.com/microsoft/inshellisense/files/13775403/inshellisense.log)

**Comment by cpendery** [comment]
@wind-mask, can you put the logs into a Github gist?

**Comment by cpendery** [comment]
Fixed by #177
