### ISSUE TITLE
Not Work in Windows Powershell

### ISSUE THREAD

**Issue by jjl9087** [microsoft/inshellisense#141]
**Describe the bug**
I installed the package following the instructions in README, but it does not work in Windows Powershell.
![powershell](https://github.com/microsoft/inshellisense/assets/88639622/208826f2-3659-4c41-9686-2b48e55e5e5e)

**Expected behavior**
It should work like what it does in pwsh.
![pwsh](https://github.com/microsoft/inshellisense/assets/88639622/179fcb2a-d47a-4ae5-b08d-69ddd6345e10)

**Environment**
 - OS: Windows 10
 - Output of `is --version`: 0.0.1-rc.6
 - Nodejs Version: v18.10.0
 - Shell: powershell
 - Shell Version: 5.1.19041.3803

**Additional context**
N/A

**Comment by simonbcn** [comment]
```
Microsoft Windows 11 Enterprise Evaluation 10.0.22621 Build 22621
PowerShell v7.4.0  
PowerShell v5.1.22621.2506
is 0.0.1-rc.6
```
It does not work for me either.

**Comment by cpendery** [comment]
Verified as working in [0.0.1-rc.8](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.8)

![image](https://github.com/microsoft/inshellisense/assets/35637443/97e6fba8-2b45-497c-8db0-e92bcdbd9087)
