### ISSUE TITLE
intelisense not working in ubuntu 20.04

### ISSUE THREAD

**Issue by avasu-rpx** [microsoft/inshellisense#142]
Intellisense not working in Ubuntu

Followed the steps in the but it didn't work readme.md.

**Environment**
 -Ubuntu 20.04
 - Output of `is --version`: throws erroe
 - Nodejs Version: v21.1.0
 - Shell: bash
 - Shell Version:5.0.17(1)-release

Tried to install it but it throws the below error
[error.txt](https://github.com/microsoft/inshellisense/files/13772336/error.txt)

**Comment by alanhg** [comment]
@avasu-rpx 

![image](https://github.com/microsoft/inshellisense/assets/9245110/240a34a2-ed48-4e5e-b270-3af70e0ad786)
![image](https://github.com/microsoft/inshellisense/assets/9245110/400827c0-9226-428e-aace-0dc456fe6567)

just use node<21. node-gyp encounters an error when installing under node@21, I understand it as its problem.
