### ISSUE TITLE
Make it possible to configure keybindings

### ISSUE THREAD

**Issue by catwang01** [microsoft/inshellisense#143]
As a vimer, I always hate `up` and `down` and want to rebind them to `ctrl+k` and `ctrl+j`. But it seems there is not way to rebind it in inshellisense.

Is there any plan to make the keybinding (tab, enter, up and down) configurable?

**Comment by alanhg** [comment]
According to the current design, I understand that it must be better to have single-character keys. For example, tab can be customized as enter. Multi-character combination keys, I understand that the current design cannot support.

**Comment by cpendery** [comment]
It's definitely possible and has become easier with the recent changes to [suggestionManager](https://github.com/microsoft/inshellisense/blob/main/src/ui/suggestionManager.ts#L159). Added to the backlog
