### ISSUE TITLE
Unable to install on Windows 11

### ISSUE THREAD

**Issue by simonbcn** [microsoft/inshellisense#145]
```
Microsoft Windows 11 Enterprise Evaluation 10.0.22621 Build 22621
Visual Studio 2022 Developer v17.8.3
node-gyp@10.0.1  C:\Users\User\AppData\Roaming\npm\node_modules\node-gyp
node@20.10.0
PowerShell v7.4.0
Python v3.12.1
```
This the output of ` npm install -g @microsoft/inshellisense`: https://gist.github.com/simonbcn/30f0244f5cfb8dc8cd6ef67ade9517ec

**Comment by simonbcn** [comment]
I was finally able to install it, after adding the libraries with the Spectre mitigations. I think the installation of this program is too complicated on Windows. Especially considering that it is being developed by the Microsoft team.

**Comment by cereschen** [comment]
It is interesting that Visual Studio 2017 can be successfully compiled when using
