### ISSUE TITLE
Does this hijack the ctrl+a?

### ISSUE THREAD

**Issue by Erimus-Koo** [microsoft/inshellisense#147]
**Describe the bug**
In MAC terminal, the default function of `Ctrl+A` is to go to the beginning of the line. 
This command is frequently used in daily tasks.
Now I press the `Ctrl+A` will directly enter the command start status, without input `is`.

![image](https://github.com/microsoft/inshellisense/assets/17139670/f06186b5-28bc-4502-bf4a-90aca80bb526)

Could I change the shortcut to others or just disable it?

**Comment by erkage** [comment]
Yes it does. It took me a few days to figure it out that this was the cause that it's not working...

However you can disable it if you delete a `bindkey` line from `~/.inshellisense/key-bindings.zsh`.
