### ISSUE TITLE
bash `syntax error near unexpected token`

### ISSUE THREAD

**Issue by flex1988** [microsoft/inshellisense#15]
**Describe the bug**
after inshellisense bind，run bash and get error `syntax error near unexpected token`

![image](https://github.com/microsoft/inshellisense/assets/7221964/114f4862-0123-41bf-a487-4145c6882d5d)

**Comment by David-Alfred** [comment]
facing the same issue

**Comment by pstachula-dev** [comment]
Same problem on zsh

**Comment by abusaidm** [comment]
Managed to solve the issue by changing the Line Sequence in the file to LF. 

Steps:
1. Open editor of choice, I used VSCode
2. Load the target file in VSCode `~/.inshellisense/key-bindings.bash` 
3. Command pallet `Change End of Line Sequence` 
4. Save file
5. reload terminal or reload file on active terminal using `source`

![image](https://github.com/microsoft/inshellisense/assets/10223047/327f56a4-b50e-47be-b2ad-cb570b02cad4)

**Comment by potyl** [comment]
@abusaidm thanks for the solution.

We can use the CLI to fix it too:

```bash
dos2unix ~/.inshellisense/key-bindings.bash
```

**Comment by cpendery** [comment]
I've updated the private build pipelines such that all the file extensions will be `LF` instead of `CRLF`. Closing and this will be included in the next pre-release.
