### ISSUE TITLE
Add Protocol protection

### ISSUE THREAD

**Issue by MasterOwnerETcorps** [microsoft/inshellisense#156]
https://www.etcorps.comi/%3D/https%3A//www.etcorps.com?_source_stat_=%7B%22page_id%22%3A%22hotsite%22%7D

**Comment by alanhg** [comment]
？？？what is?

**Comment by cpendery** [comment]
Closing due to the suspicious link and 0 issue context

**Comment by MasterOwnerETcorps** [comment]
This my bank holding sure I'm working on which is the holding comp of Microsoft I made the merger of Microsoft 365 and co-pilot thank you
..
