### ISSUE TITLE
Autocomplete for Alias in .bashrc

### ISSUE THREAD

**Issue by kevindaffaarr** [microsoft/inshellisense#157]
**Is your feature request related to a problem? Please describe.**
I have so many aliases that maybe I forget, or I do have typos when typing fast.

**Describe the solution you'd like**
It is nice to have autocompletion for the listed aliases in .bashrc

**Additional context**
I'm using windows with git-bash and listing all my setting and alias in .bashrc file.
For example, I have the alias 'pyenv_cr' for creating environment 'python311 -m venv env', it is nice if the intellisense appears by I type 'pyev...'

Thanks a lot for this opensource project.

**Comment by cpendery** [comment]
Tagging some information here as this is something Fig supports:
- https://fig.io/docs/reference/arg#parserdirectives
- https://github.com/withfig/fig/issues/792
