### ISSUE TITLE
Tryin to use it with nvm on Windows throws "SyntaxError: Unexpected reserved word"

### ISSUE THREAD

**Issue by arekgotfryd** [microsoft/inshellisense#17]
**Describe the bug**
Tryin to use it with nvm on Windows throws:
file:///C:/Users/User/AppData/Roaming/nvm/v12.22.12/node_modules/@microsoft/inshellisense/build/index.js:13
    .version(await getVersion(), "-v, --version", "output the current version")
             ^^^^^

SyntaxError: Unexpected reserved word
←[90m    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)←[39m
←[90m    at async link (internal/modules/esm/module_job.js:42:21)←[39m

**To Reproduce**
1. Open cmd
2. Install `npm install -g @microsoft/inshellisense`
3. Run `inshellisense bind`

**Expected behavior**
I expect to not get an error

**Environment**
 - OS: Microsoft Windows [Version 10.0.19045.3570]
 - Output of `inshellisense --version`: same output as in 'Describe the bug' section
 - Nodejs Version: [v12.22.12]

**Comment by yCodeTech** [comment]
> you are using outdated node version.
> 
> sudo npm install -g n sudo n lts

Windows doesn't have the sudo command....

**Comment by cpendery** [comment]
> > you are using outdated node version.
> > sudo npm install -g n sudo n lts
> 
> Windows doesn't have the sudo command....

@ycodetech I've found [this guide](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows) helpful for managing node versions on Windows & [here is the installer](https://nodejs.org/en/download) for the latest Node LTS which supports Windows. inshellisense only supports Node >= 16.X

**Comment by yCodeTech** [comment]
> > > you are using outdated node version.
> > > sudo npm install -g n sudo n lts
> > 
> > Windows doesn't have the sudo command....
> 
> @ycodetech I've found [this guide](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows) helpful for managing node versions on Windows & [here is the installer](https://nodejs.org/en/download) for the latest Node LTS which supports Windows. inshellisense only supports Node >= 16.X

Oh I know. I've had Node installed for a year or so, and l have no problems using it. I was merely stating the fact the comment using `sudo` is incorrect for Windows as it doesn't have the command internally.
