### ISSUE TITLE
Autocomplete is not working in WSL2 bash

### ISSUE THREAD

**Issue by st-man-hori** [microsoft/inshellisense#172]
**Describe the bug**
Autocomplete is not working

**To Reproduce**
1. npm install -g @microsoft/inshellisense
2. install complete
3. is -s bash
4. is -c
5. inshellisense session [live]
6. Even when typing commands like git, the autocomplete display does not appear.

**Expected behavior**
"The GUI display for autocomplete appears

**Environment**
 - OS: Windows10 WSL2 WindowsTerminal Ubuntu22.04
 - Output of `is --version`:  0.0.1-rc.7
 - Nodejs Version: v18.17.0
 - Shell: bash
 - Shell Version: GNU bash, version 5.1.16

**Additional context**
-

**Comment by cpendery** [comment]
Verified as working in [0.0.1-rc.8](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.8)

![image](https://github.com/microsoft/inshellisense/assets/35637443/16c4c9ba-7411-4318-85ae-2b80ad170155)

**Comment by whiskeyo** [comment]
@cpendery I'm running into the same problem with Debian WSL2 on Windows 11 even with 0.0.1-rc.8. Here is my setup:

```
03:24:49 whiskeyo@whiskeyo ~ → is --check
inshellisense session [live]
03:24:52 whiskeyo@whiskeyo ~ → is --version
0.0.1-rc.8
03:24:54 whiskeyo@whiskeyo ~ → cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
03:24:59 whiskeyo@whiskeyo ~ → node --version
v18.19.0
03:25:03 whiskeyo@whiskeyo ~ → bash --version
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
```

Could you recommend some actions that I could take in order to get it to work? :)

**Comment by cpendery** [comment]
@whiskeyo can I see what your prompt looks like? (feel free to strip any personal data) Also what are your PS1, PS2, and PROMPT_COMMAND environment variables set to?

**Comment by whiskeyo** [comment]
@cpendery sure, there's a screenshot with all values with both inshellisense enabled (on top) and disabled (on the bottom):

![image](https://github.com/microsoft/inshellisense/assets/36972784/e989cb4a-93d4-4997-821b-54c818c20681)

Also, here are these values if you needed to use them with inshellisense enabled:

* `PS1=\[\]03:43:36 \[\e[0;97m\]\[\e[90;1m\]\u@\h \[\e[36;1m\]\W \[\e[32;1m\]→ \[\e[0m\]`
* `PS2=>`
* `PROMPT_COMMAND=__bp_precmd_invoke_cmd _omb_util_prompt_command_hook :`

And with inshellisense disabled:

* `PS1=\[\]10:38:04 \[\e[0;97m\]\[\e[90;1m\]\u@\h \[\e[36;1m\]\W \[\e[32;1m\]→ \[\e[0m\]`
* `PS2=>`
* `PROMPT_COMMAND=_omb_util_prompt_command_hook`

If you need more details, I'll be there!

**Comment by cpendery** [comment]
Hm, it's definitely your `PROMPT_COMMAND` that's causing the issue. I've only setup shell integration for `PS1` so far and your prompt isn't giving me any issues on its own. How did you setup/install `oh-my-bash`? I'll need to replicate that for testing the fix once it's ready

![image](https://github.com/microsoft/inshellisense/assets/35637443/72ce36cd-0eb2-47c0-8733-15e80e1f601c)

**Comment by whiskeyo** [comment]
Based on my bash history, I first installed inshellisense, then moved to download curl and git, and installed oh-my-bash with `bash -c "$(...)"` command from their tutorial:

![image](https://github.com/microsoft/inshellisense/assets/36972784/1fec04e7-567a-4ba5-8628-b08488203398)

Full command is here:

```
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
```

**Comment by whiskeyo** [comment]
Also, to add some more data, here are my "most important" parts of .bashrc, some of these are automatically added by oh-my-bash during installation:

```bash
# Enable the subsequent settings only in interactive sessions
case $- in
  *i*) ;;
    *) return;;
esac

export OSH='/home/whiskeyo/.oh-my-bash'
OSH_THEME="font"
OMB_USE_SUDO=true

completions=(
  git
  composer
  ssh
)

aliases=(
  general
)

plugins=(
  git
  bashmarks
)

source "$OSH"/oh-my-bash.sh
. "$HOME/.cargo/env"
```

**Comment by cpendery** [comment]
@whiskeyo can you try if it works with the most recent change. The following command will install off main
```shell
npm uninstall @microsoft/inshellisense -g && git clone https://github.com/microsoft/inshellisense.git && cd inshellisense && npm install && npm run build && npm link
```

**Comment by whiskeyo** [comment]
@cpendery it seems to work with given command!!

![image](https://github.com/microsoft/inshellisense/assets/36972784/465b2a62-2d62-412f-a1a4-e4c5cdbb67be)

I had to add sudo to the `npm uninstall` and `npm link`, but it worked.

**Comment by cpendery** [comment]
Closing this as fixed! I'll probably cut a new release Monday that includes this along with anything else I get done.
