### ISSUE TITLE
Entering tmux with live inshellisense session breaks suggestions

### ISSUE THREAD

**Issue by whiskeyo** [microsoft/inshellisense#204]
**Describe the bug**
With inshellisense session enabled, entering `tmux` "disables" suggestions completely. Also, after first turning on `tmux` and then running `is`, everything works fine.

**To Reproduce**
1. Enable inshellisense session by `is -s bash`
2. Check if inshellisense is enabled by `is -c` (session is live)
3. Input any command, e.g. `git` - suggestions appear
4. Turn on `tmux` (my version is 3.3a), check if inshellisense is still enabled (it shows it is live)
5. Input any command, e.g. `git` - no suggestions appear

**Expected behavior**
As long as `is -c` return that session is live, I expect the session to be fully functional.

**Environment**
 - OS: Windows 11, running Debian in WSL2
 - Output of `is --version`: 0.0.1-rc.9, running on latest commit from `main`
 - Nodejs Version: v18.19.0
 - Shell: bash + oh-my-bash
 - Shell Version: 5.2.15(1)-release (x86_64-pc-linux-gnu)

**Additional context**
I got the reproduction and uploaded it to YouTube: https://www.youtube.com/watch?v=-s5pHjnGLtI

**Comment by cpendery** [comment]
@whiskeyo, since tmux is multiplexing multiple shell sessions, you'd want to start a new inshellisense session per view, rather than starting inshellisense globally. I don't think it's feasible to try to track multiple possible prompt points from one inshellisense session.
