### ISSUE TITLE
`inshellisense bind` generates windows line endings on linux

### ISSUE THREAD

**Issue by pvares** [microsoft/inshellisense#23]
**Describe the bug**

When installing bindings for `zsh` (other shells haven't been tested) the file `~/.inshellisense/key-bindings.zsh` is generated with windows line endings (`\r\n`) causing parse errors when loading: `/home/<username>/.inshellisense/key-bindings.zsh:10: parse error near '__inshellisense'`

**Workaround**
Run `dos2unix ~/.inshellisense/key-bindings.zsh`

**To Reproduce**
1. Install inshellisense on Linux
2. Run `inshellisense bind` and select `zsh`
3. Relaunch/reload shell (`source ~/.zshrc`)
4. note parse error

**Expected behavior**
Inshellisense should generate line endings appropriate to the OS

**Environment**
 - OS: Ubuntu 22.04
 - Output of `inshellisense --version`: `0.0.1-rc.1`
 - Nodejs Version: v20.9.0

**Additional context**
Running `oh my zsh`, but problem appears to continue with bare zsh as well. Original `key-bindings.zsh` file and updated `dos2unix key-bindings.zsh` files are attached (file extension changed to .txt to allow upload)

[dos2-unix-key-bindings.zsh.txt](https://github.com/microsoft/inshellisense/files/13285180/dos2-unix-key-bindings.zsh.txt)
[original-key-bindings.zsh.txt](https://github.com/microsoft/inshellisense/files/13285181/original-key-bindings.zsh.txt)

**Comment by jimkutter** [comment]
Confirmed. Having the same issue on bash. 

My Steps:

* login to new shell after installing and running `inshellisense bind`
* the following appears
```
-bash: /home/jim/.inshellisense/key-bindings.bash: line 1: syntax error near unexpected token `$'{\r''
'bash: /home/jim/.inshellisense/key-bindings.bash: line 1: `__inshellisense__() {
```
* I ran the following and the file has CRLF line endings.
```
~
jim@jim-laptop-2$ file ~/.inshellisense/key-bindings.bash
/home/jim/.inshellisense/key-bindings.bash: ASCII text, with CRLF line terminators
```
* I convert the `~/.inshellisense/key-bindings.bash` file using dos2unix as @pvares did and the error goes away and it works

**Comment by cpendery** [comment]
Thanks for reporting this! It looks like the same issue as #16, #8, & #3. I have a fix in the build pipelines for the next pre-release, so that should fix it for you.
