### ISSUE TITLE
Initialize fails in fish

### ISSUE THREAD

**Issue by filipelperes** [microsoft/inshellisense#245]
After install inshellisense and run `is init fish >> ~/.config/fish/config.fish`

why when I open my fish show
`fish: Invalid token 'C:\Users\filip\AppData\Roaming\npm\node_modules\@microsoft\inshellisense\shell\shellIntegration.fish'
. C:\Users\filip\AppData\Roaming\npm\node_modules\@microsoft\inshellisense\shell\shellIntegration.fish
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^`

**Environment**
 - OS: Windows 10
 - Output of `is --version`: 
 - Nodejs Version: 20.12.1
 - Shell: fish

**Comment by cpendery** [comment]
@filipelperes how did you install fish on Windows? I think the issue is that fish can't handle windows paths which inshellisense generates since it's running on a windows machine.
