### ISSUE TITLE
No GUI in Windows Terminal Powershell 7 (pwsh)

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [microsoft/inshellisense#249]
**Describe the bug**
The autocomplete shows a single suggestion and no GUI when using inshellisense in powershell 7 (pwsh):

![powershell 7](https://github.com/microsoft/inshellisense/assets/46269721/f30c1347-3c21-4d74-b902-9a237c28ffd5)

In comparison, this is what it does in the old powershell:

![old powershell](https://github.com/microsoft/inshellisense/assets/46269721/897a73ec-447e-4a4c-972b-642201c063ed)

**To Reproduce**
1. Install inshellisense 0.0.1-rc.14 (latest version as of writing this)
2. Open a powershell 7 shell: `"C:\Program Files\PowerShell\7\pwsh.exe" -nologo -ep bypass`
3. Start inshellisense: `is`
4. Try to use the inshellisense autocomplete. The GUI won't show up for any git commands.

**Expected behavior**
I expected the GUI to show up and allow me to select from multiple suggestions.

**Environment**
 - OS: Windows 10 Version 22H2 (OS Build 19045.4291)
 - Output of `is --version`: `0.0.1-rc.14`
 - Nodejs Version: `v19.9.0`
 - Shell: Powershell 7
 - Shell Version: PowerShell 7.4.2

**Comment by cpendery** [comment]
@ItsIgnacioPortal  can you provide the log files for the first image? You can run `is -s pwsh -V` and then paste the log files from `~/.inshellisense/inshellisense.log`

**Comment by ItsIgnacioPortal** [comment]
I've noticed that if I run pwsh.exe **directly from the Run dialog**, then cd into my user profile and then start inshellisense, the GUI does show up, albeit with the icons not loading correctly:

![inshellisense in pwsh exe](https://github.com/microsoft/inshellisense/assets/46269721/946a4a04-3f95-45c2-8072-186d8f4a1b34)

- This is the `inshellisense.log` when I run `ìs -s pwsh -V` from a Windows Terminal Powershell 7 terminal: https://gist.github.com/ItsIgnacioPortal/3920355bfdc18edab8fcecad1675a41d
- And this is the `inshellisense.log` when I run `ìs -s pwsh -V` from pwsh.exe: https://gist.github.com/ItsIgnacioPortal/f9bb9a5740d697086939a7e8abe2d86f

For testing, this is my Windows Terminal settings.json: https://gist.github.com/ItsIgnacioPortal/f1e7fb49f45794e7c3f13295b32a872a

**Comment by cpendery** [comment]
@itsignacioPortal can you retry using the most recent release `0.0.1-rc.15`? It might fix your issues or at a minimum provide more information in the log files

**Comment by ItsIgnacioPortal** [comment]
I've installed IS `0.0.1-rc.15` but the problem seems to have persisted.
These are the IS logs in the new version:
- ✅ This is the `inshellisense.log` when I run `ìs -s powershell -V` from a Windows Terminal `powershell.exe` terminal: https://gist.github.com/ItsIgnacioPortal/43f3eaad49d585f010811f6b1280eace
- ✅ This is the `inshellisense.log` when I run `ìs -s pwsh -V` from `pwsh.exe`: https://gist.github.com/ItsIgnacioPortal/85f99d0f0708589125a3d9bca9b8a876
- ❌ This is the `inshellisense.log` when I run `ìs -s pwsh -V` from a Windows Terminal `pwsh.exe` terminal: https://gist.github.com/ItsIgnacioPortal/d357d1c63338f7088a583eea6b2bd034

**Comment by cpendery** [comment]
Looking at the logs with pwsh, it's saying your cursor is at `PS C:\\Users\\User\\Github\\SecLists> git █push`. Is `push` a suggestion from the terminal? If so, that's definitely the issue.

**Comment by cpendery** [comment]
Once I merge #253 into main, you can install using this command to make sure it's working ahead of the next release
```
npm uninstall @microsoft/inshellisense -g && git clone https://github.com/microsoft/inshellisense.git && cd inshellisense && npm install && npm run build && npm link
```

**Comment by ItsIgnacioPortal** [comment]
> Looking at the logs with pwsh, it's saying your cursor is at `PS C:\\Users\\User\\Github\\SecLists> git █push`. Is `push` a suggestion from the shell? If so, that's definitely the issue and I can fix that.

Yes, push was a suggestion from the shell.

> Once I merge #253 into main, you can install using this command to make sure it's working ahead of the next release
> 
> ```
> npm uninstall @microsoft/inshellisense -g && git clone https://github.com/microsoft/inshellisense.git && cd inshellisense && npm install && npm run build && npm link
> ```

That worked! The auto-completion is now working in the normal Powershell 7. But I need it to work in Powershell 7 with oh-my-posh. Do you know how I could do that?

(Yes, I have `hello` as my terminal suffix in oh-my-posh)
- ✅ This is the inshellisense.log when I run `is -s powershell -V` from a Windows Terminal Powershell 7 terminal: https://gist.github.com/ItsIgnacioPortal/057632746d7991f8b1c1dffc6e2bce29
- ❌ This is the inshellisense.log when I run ìs -s powershell -V` from a Windows Terminal Powershell 7 terminal with oh-my-posh: https://gist.github.com/ItsIgnacioPortal/18af3cdc4ec506942c6792ae59508e6e

**Comment by cpendery** [comment]
The issue isn't your hello suffix, it's the way we parse the prompt terminator. You have the `console_title_template` set which appends to the end of your prompt. As a result, the prompt end is detected as the resolved `{.HostName}` instead of `hello`

**Comment by cpendery** [comment]
Can you try out the latest commit and let me know if it's working for you now?

**Comment by ItsIgnacioPortal** [comment]
That fix worked! Thank you.
