### ISSUE TITLE
is not working in iterm2 

### ISSUE THREAD

**Issue by netys666** [microsoft/inshellisense#255]
**Describe the bug**
is not working. whenever I type is command it goes to live but it does not show auto-completion

**Expected behavior**
It should show auto-completion

**Environment**
 - OS: Macos 13.5.2
 - Output of `is --version`: 0.0.1-rc.15
 - Nodejs Version: 16.20.2
 - Shell: zsh
 - Shell Version: 5.9 (x86_64-apple-darwin22.0)

**Additional context**
https://github.com/microsoft/inshellisense/assets/140713769/f9186ac9-6cc2-48e6-8173-142f760bedcc

**Comment by cpendery** [comment]
This should be fixed by #275 & #276

**Comment by SanditZZ** [comment]
> This should be fixed by [#275](https://github.com/microsoft/inshellisense/pull/275) & [#276](https://github.com/microsoft/inshellisense/pull/276). I'm now able to run inshellisense on macOS in iterm2 w/ zsh. Please look for release `0.0.1-rc.16` for the fixes
> 
> ![inshell](https://github.com/user-attachments/assets/4985f7f4-edd3-4c70-b518-589b8ba88faa)

Fixed! Thanks!
