### ISSUE TITLE
Fig is sunsetting, migrate to Amazon Q

### ISSUE THREAD

**Issue by listepo** [microsoft/inshellisense#258]
Effective `September 1, 2024` we will be ending access to Fig.

We encourage users to migrate to [Amazon Q for command line](https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/command-line-getting-started-installing.html). It’s free on the Individual tier and is designed to be faster and more reliable than Fig. To make this transition as easy as possible, users can upgrade to Amazon Q for command line directly from the Fig dashboard.
Any plans to support `Amazon Q`?

**Comment by vaaski** [comment]
Is inshellisense not an alternative to Fig? I only found this project because I do _not_ want anything to do with Amazon Q

**Comment by mfarr** [comment]
> Is inshellisense not an alternative to Fig? I only found this project because I do _not_ want anything to do with Amazon Q

I don't know details, but it looks like inshellisense heavily relies on Fig for at least some of its auto-complete functionality.

**Comment by cpendery** [comment]
Amazon Q (formerly Fig) and inshellisense share a dependency on this set of [autocomplete specs](https://github.com/withfig/autocomplete), so any completion that works in one should work in the other. We only rely on those specs, so sunsetting the Fig product or changes in the Amazon Q product does not affect this tool. The relationship between inshellisense and the other runtimes (Amazon Q, Fig) is equivalent of picking between Bun or Node to run a set of javascript files. The completion specs are the files that need executed and everything else is runtime specific.
