### ISSUE TITLE
Change suggestion text-color

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [microsoft/inshellisense#259]
**Is your feature request related to a problem? Please describe.**
Currently, the color of the suggestion text is solid white. This makes it difficult to differentiate between suggestion text and text that's been typed in.

![image](https://github.com/microsoft/inshellisense/assets/46269721/c3491b85-497a-4fee-8bf7-4ac450ee3b0e)

**Describe the solution you'd like**
I'd like it if there was a setting in the `.inshellisenserc` which allowed users to customize the RGB color of the suggestion text.

**Comment by cpendery** [comment]
I haven't been able to replicate this as changing the suggestion text color is definitely a bug. Closing for now, but I'll reopen if you're able to provide more details
