### ISSUE TITLE
Inshellisense error in Xonsh (0.16)

### ISSUE THREAD

**Issue by dedguy21** [microsoft/inshellisense#263]
**Describe the bug**

Getting the following error when running "is" in xonsh:
```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/node_modules/@microsoft/inshellisense/shell/shellIntegration.xsh", line 37, in <module>
    $PROMPT = "{__is_prompt_start}{__is_update_cwd}{__is_report_prompt}" + $PROMPT + "{__is_prompt_end}"
              
TypeError: can only concatenate str (not "ShellIntegrationPrompt") to str
error running xonsh run control file '/usr/lib/node_modules/@microsoft/inshellisense/shell/shellIntegration.xsh': can only concatenate str (not "ShellIntegrationPrompt") to str
```

**To Reproduce**
after adding the following to my .xonshrc and restarting xonsh:

```
# ---------------- inshellisense shell plugin ----------------
if 'ISTERM' not in ${...} and $XONSH_INTERACTIVE:
    if $XONSH_LOGIN:
        is -s xonsh --login ; exit
    else:
        is -s xonsh ; exit
```

Any time  I spawn the xonsh shell  I get that error

Spawn the xonsh shell

**Expected behavior**
I expect inshellisese to be live with no errors

**Environment**
 - OS: Arch Linux kernel 6.9.5-zen1-1-zen
 - Output of `is --version`: 0.0.1-rc.15
 - Nodejs Version: v22.3.0
 - Shell: xonsh
 - Shell Version: xonsh/0.16.0

**Additional context**
Not using a third party prompt engine like "starship", just using the default xonsh **prompt_tookit**.
Xonsh was installed using "pipx".  But it is on my path :
/home/user/.local/share/pipx/venvs/xonsh/bin
/usr/lib/python312.zip
/usr/lib/python3.12
/usr/lib/python3.12/lib-dynload
/home/air/.local/share/pipx/venvs/xonsh/lib/python3.12/site-packages
/home/user/.local/share/pipx/shared/lib/python3.12/site-packages

**Comment by drdkcisc** [comment]
I'm experiencing somthing similar in Bash through Windows Terminal
```# ---------------- inshellisense shell plugin ----------------
if [[ -z "${ISTERM}" && $- = *i* && $- != *c* ]]; then
  shopt -q login_shell
  login_shell=$?
  if [ $login_shell -eq 0 ]; then
    is -s bash --login ; exit
  else
    is -s bash ; exit
  fi
fi```

**Comment by dedguy21** [comment]
I figured out why the issue is happening.  The command "is" without any options will assume 'bash' and open it's self up in a bash shell session.

So for my situation I have to "is -s xonsh" and it will open up in a xonsh shell session.

Wasn't clear on the instructions.
