### ISSUE TITLE
Resolving shell environment fails in VSCode

### ISSUE THREAD

**Issue by danisvaliev001** [microsoft/inshellisense#266]
**Describe the bug**
[Resolving shell environment fails](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails) in VSCode after adding inshellisense configs to ~/.zshrc

**To Reproduce**
1. Execute `is init zsh >> ~/.zshrc` for install shell plugin in ZSH. Or use same for your shell.
2. Execute VSCode clicking on app icon.
3. See `Resolving Shell Environment...` message 10 seconds on Activity Bar at the bottom of the window.
4. See warning error `Unable to resolve your shell environment in a reasonable time. Please review your shell configuration and restart.`

**Expected behavior**
VSCode opening without any warnings.

**Environment**
 - OS: macOS
 - Output of `is --version`: `0.0.1-rc.15`
 - Nodejs Version: `v20.15.0`
 - Shell: `ZSH`
 - Shell Version: `zsh 5.9 (x86_64-apple-darwin23.0)`

**Comment by ZhouQiang19980220** [comment]
I have encountered the same problem, so I had to uninstall it.
