### ISSUE TITLE
Prompt doesn't show when oh-my-posh is initialized

### ISSUE THREAD

**Issue by Ripwords** [microsoft/inshellisense#267]
**Describe the bug**
Just installed it and tried to use it but no prompt was showing up. So i went to my pwsh $PROFILE and removed my oh-my-posh config and the prompts were working. I tried moving the oh-my-posh line to both before and after the inshellisense script but there's not really difference

![image](https://github.com/microsoft/inshellisense/assets/58784686/c5475d80-edbf-4f12-891f-a371a9bb3494)

![image](https://github.com/microsoft/inshellisense/assets/58784686/e1a4de02-3c47-41a5-8ecb-ea3979fbe3d0)

**To Reproduce**
1. Installed inshellisense
2. Use windows terminal with pwsh 7
3. Try inshellisense with oh-my-posh and without

**Expected behavior**
Inshellisense prompts to show up

**Environment**
 - OS: Windows 11 using pwsh 7 on terminal app
 - Output of `is --version`: 0.0.1-rc.15
 - Nodejs Version: was on v21.5, changed to v20.15.0 both have the same issue
 - Shell: Pwsh 7
 - Shell Version: PowerShell 7.4.3

**Additional context**
My pwsh $Profile
```
# Import the Chocolatey Profile that contains the necessary code to enable
# tab-completions to function for `choco`.
# Be aware that if you are missing these lines from your profile, tab completion
# for `choco` will not function.
# See https://ch0.co/tab-completion for details.
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {Import-Module "$ChocolateyProfile"}
Remove-Alias -Name ni -Force
Set-PSReadLineOption -PredictionSource None

# ---------------- inshellisense shell plugin ----------------
$__IsCommandFlag = ([Environment]::GetCommandLineArgs() | ForEach-Object { $_.contains("-Command") }) -contains $true
$__IsNoExitFlag = ([Environment]::GetCommandLineArgs() | ForEach-Object { $_.contains("-NoExit") }) -contains $true
$__IsInteractive = -not $__IsCommandFlag -or ($__IsCommandFlag -and $__IsNoExitFlag)
if ([string]::IsNullOrEmpty($env:ISTERM) -and [Environment]::UserInteractive -and $__IsInteractive) {
  is -s pwsh
  Stop-Process -Id $pid
}

oh-my-posh init pwsh --config 'C:\Users\teohj\AppData\Local\Programs\oh-my-posh\themes\agnosterplus.omp.json' | Invoke-Expression
```

**Comment by cpendery** [comment]
The inshellisense shell plugin needs to be at the very bottom of the file, after your `oh-my-posh init` command. That should fix your issue

**Comment by cpendery** [comment]
I've emphasized this detail in the readme in #279
