### ISSUE TITLE
Support for outputting variables of the current environment

### ISSUE THREAD

**Issue by Lifailon** [microsoft/inshellisense#269]
It is supported to output environment variables via `$` symbol when `echo` is called

1. Is it possible to add current session variables?

2. What other commands support outputting a list of variables, is it possible to customize this by calling a hotkey or otherwise?

3. Is it possible to add the contents of a variable to the hint (description)?

**Comment by cpendery** [comment]
They are currently supported. For customizing these outputs, feel free to make PRs to [autocomplete](https://github.com/withfig/autocomplete) since inshellisense just runs those specs.

![Image](https://github.com/user-attachments/assets/a825872a-d5ba-40df-8ba6-48d64d72594a)
