### ISSUE TITLE
Not all autocompletions are added because version is outdated

### ISSUE THREAD

**Issue by nikolaischunk** [microsoft/inshellisense#274]
**Describe the bug**
Not all of the newly added autocompletions from the `autocomplete` are added in the latest release of inshellisense.
Bumping the Version to 2.675.0 would fix this.

Reference latest version: https://www.npmjs.com/package/@withfig/autocomplete

**Comment by nikolaischunk** [comment]
#271

**Comment by cpendery** [comment]
We pegged the version to `2.651.0` to avoid some missing implementation in shellisense. I'll need to do some more testing before just accepting the version bump
