### ISSUE TITLE
`conda` not working within the `inshellisense` instance

### ISSUE THREAD

**Issue by brianferri** [microsoft/inshellisense#286]
**Describe the bug**
Once an `inshellisense` shell has been spun up it is impossible to access any `conda` environment

**To Reproduce**
1. Open any terminal
2. Start an `inshellisense` shell (non-login due to https://github.com/microsoft/inshellisense/issues/285)
3. Activate a `conda` environment using `conda activate` or by opening a project in VSCode that supports local `.conda` env
4. See that by doing `which python` the path is not the one from the selected environment

**Expected behavior**
I'd expect that the `conda` environment would get activate as usual, showing the correct path when queried and allow the user to access the dependencies which are installed in that environment

**Environment**
- OS: [e.g. iOS] MacOS Sonoma 14.6.1 (23G93)
- Output of is --version: 0.0.1-rc.16
- Nodejs Version: [e.g. 20.9.0] v22.2.0
- Shell: [e.g. bash, zsh, fish] zsh
- Shell Version: [e.g. 5.2.21] zsh 5.9 (x86_64-apple-darwin23.0)

**Additional context**
I installed the `miniconda` distribution from https://docs.anaconda.com/miniconda/
running conda 23.11.0

**Comment by brianferri** [comment]
@cpendery you added this issue to an already closed milestone. Bringing it to your attention just in case it was a mistake.

**Comment by cpendery** [comment]
This should be fixed in 0.0.1-rc.17 which is releasing shortly. Please run `is doctor` after installing and fix any of the recommendations before retrying

![Image](https://github.com/user-attachments/assets/e5b4c0fc-758a-49c2-bf34-3beb84ac94f0)
