### ISSUE TITLE
spaces on files/folder names are not escaped

### ISSUE THREAD

**Issue by thomasphansen** [microsoft/inshellisense#289]
**Describe the bug**
Using bash. Consider a folder named "my backup". If I type "cd ", the autocomplete will show me the proper folder name, but when I select it, it will come without the escape character for the space (like "my\ backup"), causing the cd command to fail with the message "bash: cd: too many arguments". 

**To Reproduce**
1. Create a folder in your current location called "my test"
2. Start "is"
3. type "cd "
4. Select the option "my test"
5. Press enter

**Expected behavior**
Selecting the "my test" folder from "is" list should result in a properly escaped result, like "cd my\ test". The escape pattern should follow the same rules as when we press "tab" in a bash shell.

**Environment**
 - OS: Linux Mint 21.3
 - Output of `is --version`: 0.0.1-rc.16
 - Nodejs Version:20.15.0
 - Shell: bash
 - Shell Version: 5.1.16(1)-release (x86_64-pc-linux-gnu)

**Additional context**

**Comment by cpendery** [comment]
I can't replicate this, can you provide your logs from `~/.inshellisense/inshellisense.log` after running inshellisense with `-v`? (please make sure to not run any commands with as it captures all the content that appears on the terminal screen).

**Comment by cpendery** [comment]
Closing this due to lack of response. Let's see if this is an issue with `0.0.1-rc.17`
