### ISSUE TITLE
Can you please remove the windows newlines from the keybind bash file

### ISSUE THREAD

**Issue by ghostbust555** [microsoft/inshellisense#3]
install inshellisense
run inshellisense bind
notice starting bash now gives a fun error
dos2unix the keybind.bash file inshellisense generated
notice it is no longer an issue

**Comment by alex-kinokon** [comment]
For people searching the error message:

```
/Users/me/.inshellisense/key-bindings.zsh:10: parse error near `__inshellisense'
```

**Comment by joshryandavis** [comment]
thanks. this was really confusing me.

**Comment by cpendery** [comment]
I've updated the private build pipelines such that all the file extensions will be `LF` instead of `CRLF`. Closing and this will be included in the next pre-release.
