### ISSUE TITLE
add support for Node.js 22.X

### ISSUE THREAD

**Issue by Kinson261** [microsoft/inshellisense#304]
**Describe the bug**
I tried installing inshellisense on Fedora 41 but it doesn't work.

**To Reproduce**
run: npm install -g @microsoft/inshellisense

**Expected behavior**
npm error code ETARGET
npm error notarget No matching version found for @microsoft/inshellisense@*.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.

**Environment**
 - OS: Fedora 41
 - Nodejs Version: v22.11.0
 - Shell: zsh
 - Shell Version: zsh 5.9 (x86_64-redhat-linux-gnu)

**Comment by peterclemenko** [comment]
similar problem on fresh install of win 11

**Comment by ilnarb** [comment]
similar problem
`npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@microsoft/inshellisense@0.0.1-rc.18',
npm warn EBADENGINE   required: { node: '>=16.6.0 <21.0.0' },
npm warn EBADENGINE   current: { node: 'v22.11.0', npm: '10.9.1' }
npm warn EBADENGINE }`

**Comment by JassVirk4700** [comment]
**PROBLEM SOLVED while installing** 

Initially I tried to install by having these config of pc:
OS: Windows 11 (actually doesn't matter)
Node.js : v23.3.0(latest) or v22.12.0
npm: latest version

But this happen:

command (powershell): npm install -g @microsoft/inshellisense

error:
npm error code ETARGET
npm error notarget No matching version found for @microsoft/inshellisense@*.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: C:\Users\hp\AppData\Local\npm-cache\_logs\2024-12-04T09_23_58_922Z-debug-0.log

**### BUT, to solve this problem & run inshellisense on your computer**
You have to uninstall node.js latest version & install old version{ node: '>=16.6.0 <21.0.0' }, then run the same command for installing inshellisense [ **npm install -g @microsoft/inshellisense** ] then it will get install & to check whether it is installed or not run command [ is -c ] & the terminal will return something like image attached.

Hope, it helps 🙏🏻![Image](https://github.com/user-attachments/assets/3a746739-39e8-46fb-a2db-7e64089f7cd7)

**Comment by gluons** [comment]
I force install and specify `latest` version. It works
This is my workaround.

```
npm install -g -f @microsoft/inshellisense@latest
```

**Comment by Kinson261** [comment]
For those using fedora (or any other linux distribution) , I found a temporary workaround in order to enjoy inshellisense before it supportting newer version of Node.js

For Fedora 41, you can downgrade Node.js to its version in Fedora 40 using:

    sudo dnf downgrade --releasever=40 nodejs

To prevent it from upgrading, you can lock the version using:

    sudo dnf versionlock add nodejs

For any other distro, please refer to Node.js version used in earlier version.
