### ISSUE TITLE
Can't install using npm

### ISSUE THREAD

**Issue by Freemorger** [microsoft/inshellisense#307]
**Describe the bug**
Can't install it using npm (as meant to). Getting error:
 sudo npm install -g @microsoft/inshellisense
```
(node:25632) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm error code ETARGET
npm error notarget No matching version found for @microsoft/inshellisense@*.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```

**To Reproduce**
1. try to install it using npm:
`sudo npm install -g @microsoft/inshellisense`

**Expected behavior**
installation complete

**Environment**
 - OS: Arch Linux
 - Output of `is --version`: 
 - Nodejs Version: 23.1.0
 - Shell: zsh
 - Shell Version: 5.9

**Additional context**

**Comment by raphaelcruzeiro** [comment]
Same result on macOS 15.2 (24C101)

**Comment by BindingOx** [comment]
downgrade to Node.js 20.X

**Comment by cpendery** [comment]
Only LTS versions are supported, I just added support for 22
