### ISSUE TITLE
Unsupported shell: '', supported shells: bash, powershell, pwsh, zsh, fish

### ISSUE THREAD

**Issue by engureguo** [microsoft/inshellisense#39]
**Describe the bug**
After installing, I meet this When I do this:
![image](https://github.com/microsoft/inshellisense/assets/57861661/669b46a9-00d9-40ac-b658-402c6034ced4)

**To Reproduce**

**Expected behavior**

**Environment**
 - OS: Win11
 - Output of `inshellisense --version`:  0.0.1-rc.3
 - Nodejs Version: [e.g. 20.9.0] v20.8.0

**Additional context**

**Comment by korewaChino** [comment]
Having the same issue on Linux

**Comment by reisir** [comment]
It expects you to run `inshellisense --shell <shell>` but I agree, it should use the current shell by default.

**Comment by oosame** [comment]
same on ubuntu, running 
```bash
inshellisense -s (which fish)
```

**Comment by Delta456** [comment]
If no argument is passed then it must print `help` so that the user knows what to use accordingly.

**Comment by aliuq** [comment]
If I typed `inshellisense`, hope to use the current shell

**Comment by ngaini-n-able** [comment]
Having the same issue on Mac 
Unsupported shell: '', supported shells: bash, pwsh, zsh, fish

**Comment by cpendery** [comment]
> Having the same issue on Mac Unsupported shell: '', supported shells: bash, pwsh, zsh, fish

You should see this fixed in the next release `0.0.1-rc.4`
