### ISSUE TITLE
inshellisense bind does not work when powershell config file is within onedrive

### ISSUE THREAD

**Issue by ggayan** [microsoft/inshellisense#4]
**Describe the bug**
![image](https://github.com/microsoft/inshellisense/assets/136873/64a5e329-ac6a-4d97-b486-4dea22a81a54)

**Comment by AmirRezaei** [comment]
Same problem here.

**Comment by philibertperusse** [comment]
Same issue, I tracked down the problem to 'utils\bindings.js' where the path built from using os.homedir(). For the bind, to support properly with OneDrive, it should query poweshells $PSScriptRoot variable to get proper start directory.
