### ISSUE TITLE
Support PSReadLine 

### ISSUE THREAD

**Issue by doggy8088** [microsoft/inshellisense#46]
**Is your feature request related to a problem? Please describe.**
I want `PSReadLine` when use `inshellisense --shell pwsh` enter the inshellisense environment.

**Describe the solution you'd like**
I want all the keyboard shortcut from PSReadLine back.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cpendery** [comment]
This is most likely a similar fix to the other issues with prompts and other extensions @doggy8088. I'm actively investigating a good solution for this 👍

**Comment by cpendery** [comment]
Closing as this was fixed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)
