### ISSUE TITLE
Generators don't seem to work

### ISSUE THREAD

**Issue by rajyraman** [microsoft/inshellisense#48]
I tried to get the most [basic generator](https://fig.io/docs/reference/generator/basic) working in pwsh but no suggestions are being shown. Since _dotnet package add_ is also using generator, I thought I will test that but no dynamic suggestions for package is being shown. So, it does not appear to work at all. 

inshellisense: 0.0.1-rc.3
node: v18.18.0

**Comment by cpendery** [comment]
Hey @rajyraman, I don't see `dotnet package` as a command that's been implemented by fig ([dotnet's base spec](https://github.com/withfig/autocomplete/blob/master/src/dotnet.ts) & [dotnet's subcommand specs](https://github.com/withfig/autocomplete/tree/master/src/dotnet). If I try something like `git add ` in **pwsh**, I'm able to see generator suggestions for the git commands 

<img src="https://github.com/microsoft/inshellisense/assets/35637443/e4f2b4e9-e7b9-4c19-88ea-3ac08f26532a" height="200px"/>

**Comment by cpendery** [comment]
If you like to add support for it, I'm sure they'd be happy to receive a PR for it

**Comment by cpendery** [comment]
@rajyraman where are you putting this generator? Right now, `inshellisense` doesn't support fig's dev mode for testing new specs. 

Can you run `git --no-optional-locks status --short` in the same repository and provide the output?

**Comment by rajyraman** [comment]
@cpendery - I build my autocomplete module with yarn dev and copied the js to inshellisense withfig's build folder. I also added the module to index.js
![image](https://github.com/microsoft/inshellisense/assets/5035266/f321d858-0968-4c50-86bc-d7a9a358789d)

Below is the output of the git command.
![image](https://github.com/microsoft/inshellisense/assets/5035266/61e6f1d8-7517-493c-bed5-b5f0143b6bff)

**Comment by cpendery** [comment]
You'd need to update the `index.js` file as well to get that to work

**Comment by rajyraman** [comment]
@cpendery - Yes. I was already doing that.

**Comment by rajyraman** [comment]
@cpendery - I already have pac working locally. Just need to add the generator bits.

https://x.com/RajYRaman/status/1722342461018984470?s=20
