### ISSUE TITLE
Cannot find module when press ctrl+a to tigger completion

### ISSUE THREAD

**Issue by techstay** [microsoft/inshellisense#50]
**Describe the bug**
The prompt failed to find its dependencies to launch. When I use `Ctrl+A` to trigger the completion, it raises such errors.

```sh
node:internal/modules/cjs/loader:1051
  throw err;
  ^                                                                                                                     
Error: Cannot find module 'C:\Users\asddf\AppData\Roaming\npm\node_modules\@microsoft\inshellisense\build\index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.9.0
```

**To Reproduce**
After installation, press `ctrl+a` and it raises the errors.

**Expected behavior**
proper completion

**Environment**
 - OS: windows 11
 - Output of `inshellisense --version`: 0.0.1-rc.3
 - Nodejs Version: v20.9.0

**Additional context**
I use scoop to install nodejs-lts package, so the installation path may differ from the normal installation.
```sh
❯ which npm
C:/Users/asddf/scoop/apps/nodejs-lts/current/bin/npm.cmd
❯ which inshellisense
C:/Users/asddf/scoop/apps/nodejs-lts/current/bin/inshellisense.cmd
```

**Comment by cpendery** [comment]
@techstay which shell is this in and you're still able to successfully run `inshellisense --version`? Can you try directly running `inshellisense` via `inshellisense -s <shell>`

**Comment by BrightXiaoHan** [comment]
same problem
![image](https://github.com/microsoft/inshellisense/assets/25839309/54e452d5-9fc2-4f4e-b1c7-7b13e0414771)

**Comment by ilkerhalil** [comment]
Same problem.
![image](https://github.com/microsoft/inshellisense/assets/5356826/5ea52a8b-8cbe-433d-b7af-7adfe28077f9)

**Comment by techstay** [comment]
> @techstay which shell is this in and you're still able to successfully run `inshellisense --version`? Can you try directly running `inshellisense` via `inshellisense -s <shell>`

I use pwsh and running inshellisense -s <shell>` works fine. Just like other guys here.

**Comment by Devil-SX** [comment]
Same problem. I use MSYS2-bash on Windows

![image](https://github.com/microsoft/inshellisense/assets/77198466/14e29f6c-721b-409d-bc46-d4e2e9f21a0d)

**Comment by anthea-wu** [comment]
I solve this problems by below steps:
1. open power shell and types `npm config get prefix` to check where npm install
2. finding your `key-bindings-powershell.ps1`, replace `$inshellisense` to your npm install path

for example:
1. original `$inshellisense` in `key-bindings-powershell.ps1` is `$env:USERPROFILE\AppData\Roaming\npm\node_modules\@microsoft\inshellisense\build\index.js`
2. my npm install in `C:\Program Files\nodejs\node_modules`
3. change `$inshellisense` to `c:\PROGRA~1\nodejs\node_modules\@microsoft\inshellisense\build\index.js`

be aware of `Program Files`, it has a whitespace, so need to write to `PROGRA~1`.

hopes this answer helpful.

**Comment by Monarch510** [comment]
same problem
![image](https://github.com/microsoft/inshellisense/assets/32095219/40f618c8-98d7-4494-91e6-01bbb4e03db5)
environment:
os: win10
node: v20.2.0
inshellisence: 0.0.1-rc.4

**Comment by Monarch510** [comment]
https://github.com/microsoft/inshellisense/issues/50#issuecomment-1820566295
Refer to the above practice。
### Here are a few things I added：
1.`key-bindings-powershell.ps1` in `[you node.js install path]\node_global\node_modules\@microsoft\inshellisense`.
2.After change file 'key-bindings-powershell.ps1', please run './key-bindings-powershell.ps1'.

**Comment by cpendery** [comment]
Closing as the ctrl-a binding was removed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)
