### ISSUE TITLE
Aliases do not seem to work for zsh

### ISSUE THREAD

**Issue by Khalian** [microsoft/inshellisense#54]
**Is your feature request related to a problem? Please describe.**
Yes. I tried setting up aliases (like alias rootdir="/") but then cant use it. 

**Describe the solution you'd like**
aliases should work just like vanilla zsh. 

**Describe alternatives you've considered**
I do not have one.

**Comment by Muffeter** [comment]
i wrote this: #71

**Comment by cpendery** [comment]
Closing as this was fixed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)
