### ISSUE TITLE
Typing "ls -" does not jump you to the options for the ls command

### ISSUE THREAD

**Issue by abulka** [microsoft/inshellisense#56]
**Describe the bug**
Typing `ls -` does not jump you to the options for the ls command, I have to scroll past potentionally dozens of filenames (depending on the contents of the directory) to get to the parameters for the `ls` command.

**To Reproduce**
1. Type `ls `
2. Notice the filenames in the current dir are suggested, but not the options like `-h` etc.
3. Type `-`
4. I still am stuck on viewing filenames, and the options like `-h` etc. are not visible, I have to scroll down pages to get to them.

**Expected behavior**
Hitting `-` should jump you to the options of the `ls` command, just like `find -` does and many other commands.

**Environment**
 - OS: macox
 - Output of `inshellisense --version`: 0.0.1-rc.4
 - Nodejs Version: v18.16.0

**Additional context**
Perhaps hitting up arrow to backwards scroll (or some other key) would bypass filenames and get to the options of a command. Getting to the options of a command is, after all, the main point of inshellisense, so making it easy to get to the options is essential.

**Comment by cpendery** [comment]
I'm not able to replicate this on `0.0.1-rc.4`. Which shell are you using @abulka?

**Comment by Alishtan25** [comment]
Please میشه راهنمایی کنید منو که تو این مارکت مشکل کاره من کجاست ک نمی تونم ب درامد برسم و چرا حساب کیف پولم توش پول نمیشینه یا حسابام بسته میشه کی داره این بازی رو کش میده

**Comment by Alishtan25** [comment]
تمام حساب های alishtan25@gmail.com رو بهت میدم ۸۰% من ۲۰% هرکسی ک حسابمو باز کرد یا یه اندیکاتور واس حساب trading View بنویسه ک ب حساب ریالیم متصل شه و ۹تریالد دلار رو نقد کنیم یک تریلیارد دلار مال شما .منو تو فیس بوک یا تویتر@Gazmeh Ali یا ایمیلم جواب بده و کد#۱رو اول پستت بزار تا زودتر متوجه شم.

**Comment by abulka** [comment]
> I'm not able to replicate this on `0.0.1-rc.4`. Which shell are you using @abulka?

zsh

**Comment by Muffeter** [comment]
hello @abulka, i've fixed this bug. You can try this  #66 .
