### ISSUE TITLE
Piping into another command - inshellisense does not work on that other command

### ISSUE THREAD

**Issue by abulka** [microsoft/inshellisense#57]
**Is your feature request related to a problem? Please describe.**
I want to use Inshellisense on multiple commands when constructing more complex command line invocations that use pipes. For example
```
ls | cat -
```
should bring up the options for the `cat` command. But I don't get any options, just a list of filenames, which is useless, as I am piping into `cat` and don't need to supply a filename. 

**Describe the solution you'd like**
```
ls | cat -
```
should bring up the options for the `cat` command

**Comment by cpendery** [comment]
Thanks for the great example, I'm able to replicate this and will start working on a fix
