### ISSUE TITLE
Git bash for windows throws an Ink exception

### ISSUE THREAD

**Issue by CommandCrafterHD** [microsoft/inshellisense#58]
**Describe the bug**
Running `is -s bash` in a git bash for windows terminal, throws the exception
```
 ERROR Raw mode is not supported on the current process.stdin, which Ink uses
       as input stream by default.
       Read about how to prevent this error on
       https://github.com/vadimdemedes/ink/#israwmodesupported
```

**To Reproduce**
1. Start a git bash terminal
2. Run `is -s bash`
3. See error

**Expected behavior**
Inshellisense launches as expected.

**Environment**
 - OS: Windows 10
 - Output of `inshellisense --version`: 0.0.1-rc.4
 - Nodejs Version: [18.16.0]

**Comment by cpendery** [comment]
Are you using git bash standalone? You'll need to enable raw mode in cygwin/mintty to use `inshellisense`. Different terminal emulators like xterm.js in VSC will already have it enabled.

**Comment by cpendery** [comment]
Follow [this guide](https://github.com/mintty/mintty/wiki/Tips#inputoutput-interaction-with-alien-programs) and set your git bash config at `/etc/git-bash.config` to set `MSYS=enable_pcon`. I was able to replicate your issue, and this resolved it.
