### ISSUE TITLE
UI/UX is bad

### ISSUE THREAD

**Issue by LatticeMage** [microsoft/inshellisense#59]
**Is your feature request related to a problem? Please describe.**
UX is bad, when we see an option, we usually press Enter, not tab due to the UI

**Describe the solution you'd like**
I think it is better to make the unfinished part is gray and hint user this command is not finished, and use tab to choose the result
![image](https://github.com/microsoft/inshellisense/assets/127104465/9f917772-1da6-4ef9-b3ea-0abcba9f1bf2)
![image](https://github.com/microsoft/inshellisense/assets/127104465/b518d4b5-94e2-4dff-9cdf-b5813e5c59a8)

**Describe alternatives you've considered**
not showing the option list, just gray letters for hint to press tab to fulfill

**Additional context**
N/A

**Comment by cpendery** [comment]
The ghost text is an interesting idea, but I feel like it gives more a copilot feel than intellisense. I'll look into potentially making this a configurable UI option.

**Comment by genie360s** [comment]
I think , we can think it of more like good design practices , rather than relating it to copilot feels , since gmail , also uses the design concept etc.

**Comment by theKnightsOfRohan** [comment]
It could also be a good idea to have enter also trigger autocomplete

**Comment by genie360s** [comment]
Very true!

**Comment by cpendery** [comment]
> It could also be a good idea to have enter also trigger autocomplete

If a user doesn't want to accept a submission, would you expect them to hit something like `ESC` and then enter to run the command? It feels like a breaking experience for most shell users where enter is always execute the command.

**Comment by LatticeMage** [comment]
or if there is some setting file let user to choose his/her own key

**Comment by theKnightsOfRohan** [comment]
> > It could also be a good idea to have enter also trigger autocomplete
> 
> 
> 
> If a user doesn't want to accept a submission, would you expect them to hit something like `ESC` and then enter to run the command? It feels like a breaking experience for most shell users where enter is always execute the command.

Well, inshellisense is simulating actions which most often occur in an ide, and in most ides, that's how the intellisense works. One way to improve this would be adding some simple settings, and/or having the UI disappear when using arrow keys to navigate your line.

**Comment by cpendery** [comment]
I'll look into making some of the actions, like accepting a suggestion, configurable. For ghost text, it will not be added to inshellisense due to #79. I'm going to allow users to leverage the built in shell suggestions while also viewing inshellisense suggestions, so ghost text will be reserved for the shell's builtin suggestions (zsh-autocomplete, fish, pwsh).
