### ISSUE TITLE
Unable to autocomplete a git command

### ISSUE THREAD

**Issue by adder32** [microsoft/inshellisense#6]
**Describe the bug**
Inshellisense is unable to autocomplete a git command.

**To Reproduce**
Start `is` (with `is --shell bash`), and try typing up a git command, such as `git log --graph --decorate --pretty=oneline --abbrev-commit --all`

**Expected behavior**
Currently, when I type `g`, the only option is `--grep`. `d` offers no options. `p` offers `--patch`. `a` offers `--all`.
This should be able to find all the options that git (or any command) offers.

**Environment**
 - OS: Xubuntu 22.04.1
 - Output of `inshellisense --version`: `0.0.1-rc.1`
 - Nodejs Version: v20.6.1

**Comment by cpendery** [comment]
Hey @adder32, it looks like this is an issue with the underlying Fig autocomplete spec for `git log`, [options shown here](https://github.com/withfig/autocomplete/blob/8256af79a4811d84632dcc3c980bb814c26fa871/src/git.ts#L6259-L6299). I'm sure they'd be happy to accept a PR fixing this, but this isn't an issue with inshellisense's execution of the spec. I'm going to close this, but please feel free to open up an issue on their repo.
