### ISSUE TITLE
Stop working when typing

### ISSUE THREAD

**Issue by nep-0** [microsoft/inshellisense#62]
**Describe the bug**
Typing something, then cannot type anymore.

**To Reproduce**
1. type `gcc lab2/5.2.c -`
2. cannot type anymore

**Expected behavior**
Typing something, then cannot type anymore.

**Environment**
 - OS: Windows 22621.2506
 - Output of `inshellisense --version`: `0.0.1-rc.4`
 - Nodejs Version: v20.9.0

**Comment by cpendery** [comment]
Thanks for reporting this! I'm able to replicate this and will work on a fix
