### ISSUE TITLE
Zsh: cd command does not change the directory

### ISSUE THREAD

**Issue by RaidOuahioune** [microsoft/inshellisense#69]
**Environment**
 - OS: Ubuntu 22.04
 - inshellisense version: 0.0.1-rc.4 
 - Nodejs Version: v20.5.1

**Comment by inRm3D** [comment]
similar to https://github.com/microsoft/inshellisense/issues/11

**Comment by cpendery** [comment]
Closing as this was fixed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)
