### ISSUE TITLE
repeat suggests  when use Hyper terminal with ZSH

### ISSUE THREAD

**Issue by gasparsuarez** [microsoft/inshellisense#73]
**Describe the bug**
When you write a command, the options start to be repeated many times in the console.
In default terminal of mac, work correctly.

**To Reproduce**
Any command

**Expected behavior**

**Environment**
 - OS: [MACOS Sonoma 14.1]
 - Output of `inshellisense --version`: 0.0.1-rc.4
 - Nodejs Version: [18.18.2]

**Additional context**

**Comment by cpendery** [comment]
Closing as this was fixed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)
