### ISSUE TITLE
It seemed that I can't execute any command which inshelllisense don't support in the session

### ISSUE THREAD

**Issue by cycode0527** [microsoft/inshellisense#75]
在会话中,我不能执行任何is不支持的命令,例如history等,如下:

```bash
> history
zsh:fc:1: no such event: 1
```

另外,session缺少语法高亮,没有命令别名alias,和上述问题一起,造成了session使用的割裂感.

话说我还不能用方向键来获得过往命令,以及在session中输入的命令无法存入history

**Comment by cycode0527** [comment]
sorry, it's my first issue. I think I had given my issue a wrong label.

It seemed that feature-request instead of bug

**Comment by cpendery** [comment]
Closing as this should have been fixed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)
