### ISSUE TITLE
Will i18n supported?

### ISSUE THREAD

**Issue by Giftia** [microsoft/inshellisense#76]
**Is your feature request related to a problem? Please describe.**
The explanation of autocomplete is not support i18n now.

**Describe the solution you'd like**
Supports i18n, good for people who use English as a second language.

**Describe alternatives you've considered**
I still use Google Translate when I'm confused about the explanation of a command.

**Additional context**
Expect like this: (I'm using Simplified Chinese language package)
![image](https://github.com/microsoft/inshellisense/assets/12429652/b47bd797-55b0-44fc-9f7a-7fbd992cbc50)
```[tasklist]
### Tasks
```

**Comment by cpendery** [comment]
Hi @Giftia, I don't plan on supporting i18n currently as fig's [specs](https://github.com/withfig/autocomplete) don't support i18n

**Comment by niStee** [comment]
[Opened discussion](https://github.com/orgs/withfig/discussions/2854) at fig's.
