### ISSUE TITLE
Not Work in PowerShell 7

### ISSUE THREAD

**Issue by CoderLittleChen** [microsoft/inshellisense#77]
OS:Windows 10. 
I installed the package but not work.

<img width="1144" alt="1" src="https://github.com/microsoft/inshellisense/assets/32502670/00515a7b-1705-4b3d-b5e7-a37e3cc0a50f">

<img width="1146" alt="2" src="https://github.com/microsoft/inshellisense/assets/32502670/7b1164ad-bd22-4583-af95-52c437a30f59">

**Comment by Giftia** [comment]
`inshellisense` is temporarily incompatible with `oh-my-posh` (see #19). I guess you may want to run `is -s powershell` or hot key `CTRL + a`. See [Quickstart](https://github.com/microsoft/inshellisense#quickstart).
> `inshellisense` 暂时与 `oh-my-posh` 不兼容（详见 #19）。我猜你想要的效果是运行 `is -s powershell` 或者是快捷键 `ctrl+a` ，如果你有认真看过使用说明的话：[快速入门](https://github.com/microsoft/inshellisense#quickstart)。

![image](https://github.com/microsoft/inshellisense/assets/12429652/6bd5969b-6f39-4c38-897f-31f877c99688)

**Comment by CoderLittleChen** [comment]
> `inshellisense` is temporarily incompatible with `oh-my-posh` (see #19). I guess you may want to run `is -s powershell` or hot key `CTRL + a`. See [Quickstart](https://github.com/microsoft/inshellisense#quickstart).
> 
> > `inshellisense` 暂时与 `oh-my-posh` 不兼容（详见 #19）。我猜你想要的效果是运行 `is -s powershell` 或者是快捷键 `ctrl+a` ，如果你有认真看过使用说明的话：[快速入门](https://github.com/microsoft/inshellisense#quickstart)。
> 
> ![image](https://user-images.githubusercontent.com/12429652/282691502-6bd5969b-6f39-4c38-897f-31f877c99688.png)

I got it, Thank you guys

**Comment by noam-isaac** [comment]
> A bit more context around this issue: I'm on Windows 11 23H2. I get this issue in Windows Powershell and on Powershell 7, but it works flawlessly on Git Bash.

I am also getting the same issue on 23H2 (10.0.22631).

**Comment by cpendery** [comment]
Closing as this should be fixed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)

**Comment by tiagofassoni** [comment]
Thank you! I liked this software so much I actually had a reminder to look
for updates of it mid-January
