### ISSUE TITLE
The "command" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by floriaaan** [microsoft/inshellisense#81]
**Describe the bug**
It seems that installing inshellisense using pnpm cause to print error when writing commands especially `pnpm add -g`

**To Reproduce**

Just after installing inshellisense using pnpm
Write `pnpm add -g pnpm`

**Expected behavior**
Not to print 
`{
  error: TypeError [ERR_INVALID_ARG_TYPE]: The "command" argument must be of type string. Received an instance of Object
      at new NodeError (node:internal/errors:399:5)
      at validateString (node:internal/validators:163:11)
      at normalizeExecArgs (node:child_process:188:3)
      at exec (node:child_process:231:16)
      at file:///Users/floriaaan/Library/pnpm/global/5/.pnpm/@microsoft+inshellisense@0.0.1-rc.4/node_modules/@microsoft/inshellisense/build/runtime/utils.js:8:9
      at new Promise (<anonymous>)
      at file:///Users/floriaaan/Library/pnpm/global/5/.pnpm/@microsoft+inshellisense@0.0.1-rc.4/node_modules/@microsoft/inshellisense/build/runtime/utils.js:7:12
      at f (file:///Users/floriaaan/Library/pnpm/global/5/.pnpm/@withfig+autocomplete@2.640.3/node_modules/@withfig/autocomplete/build/pnpm.js:1:1143)
      at file:///Users/floriaaan/Library/pnpm/global/5/.pnpm/@withfig+autocomplete@2.640.3/node_modules/@withfig/autocomplete/build/pnpm.js:1:1263
      at Generator.next (<anonymous>) {
    code: 'ERR_INVALID_ARG_TYPE'
  }
}`

**Environment**
 - OS: macOS Sonoma 14.2
 - Output of `inshellisense --version`: 0.0.1-rc.4
 - Nodejs Version: v18.16.1

**Comment by cpendery** [comment]
Closing as this was fixed since we no longer depend on key bindings in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)

**Comment by John-P** [comment]
I still have this same error on 0.0.1-rc.7
