### ISSUE TITLE
Loading autocompletion specs from outside the withfig/autocomplete repo

### ISSUE THREAD

**Issue by pzmarzly** [microsoft/inshellisense#83]
In https://github.com/withfig/fig/issues/2828 I've proposed to make Fig start loading autocompletion specs from a local directory (e.g. `/usr/share/fig-autocomplete/mycli.json`) in addition to [withfig/autocomplete](https://github.com/withfig/autocomplete) repo. This has some benefits, such as not being tied down to 1 company, being able to create autocomplete specs for internal (confidential) CLIs without publishing them to the wide world, and more (see the list issue).

I'm opening the issue here for visibility and to encourage discussion under original link. I think that it's in best interest of Inshellisense to support that, and if Fig implemented it, Inshellisense may want to follow soon.

**Comment by cpendery** [comment]
Fig already supports loading specs locally as mentioned in their docs [here](https://fig.io/docs/handbook/how-does-fig-load-specs).

**Comment by pzmarzly** [comment]
Aaah i missed that! Still, it supports `~/.fig/autocomplete/build` but nothing machine-wide (`/usr/share/...`)

**Comment by hustcer** [comment]
I need this feature badly. Can it has a higher priority ？Thanks

**Comment by alanhg** [comment]
> I need this feature badly. Can it has a higher priority ？Thanks

Try installing the latest version.

![image](https://github.com/microsoft/inshellisense/assets/9245110/41709c3a-f43a-43e3-85b2-cb09dac0c82e)
