### ISSUE TITLE
Homebrew installation would be incredibly helpful and increase adoption

### ISSUE THREAD

**Issue by ylluminate** [microsoft/inshellisense#84]
Many folks are accustomed to using Homebrew or MacPorts on macOS to install and update apps. Having Inshellisense installable and updated via this would really help adoption and uptake. I know many folks that just don't mess with things anymore unless there's a Homebrew tap or it's on MacPorts.

**Comment by cpendery** [comment]
Duplicate of #82

**Comment by cpendery** [comment]
Closing as duplicate of #199
