### ISSUE TITLE
Leave the inshellisense mode, atleast by pressing keybind or remove it completely

### ISSUE THREAD

**Issue by MustCodeAl** [microsoft/inshellisense#86]
**Is your feature request related to a problem? Please describe.**
so Instead of using ctrl + a, i found it better to use ctrl + space, but there is no way to exit in the inshellisense without entering exit command

https://github.com/microsoft/inshellisense/assets/87888006/523a87bc-531d-49bd-9fa8-f38ae56d157a

**Describe the solution you'd like**
A better feature would be to just have the completions popup automatically and close one selected or when pressing keybind, and keeping the same prompt and theme, instead of the built in interactive mode 

**Describe alternatives you've considered**
trying to current figure out to make the key-bind a toggle for the completion and exit, but im not sure on how to about doing so

**Additional context**
hoping for in the future the ability to just use ones shell prompt already there rather than abandoning it for the inshellisense one

**Comment by cpendery** [comment]
Feel free to check out #79 for better support of one's shell prompt & default functionality. I think this should resolve your issue though I'll look at adding a custom keybinding to leave inshellisense in the future

**Comment by cpendery** [comment]
Closing as full shell support was added in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5) & now `esc` will take you out of the current suggestions
