### ISSUE TITLE
Cannt in powershell

### ISSUE THREAD

**Issue by kametsun** [microsoft/inshellisense#88]
**Describe the bug**
After downloading inshellisense, I was unable to start powershell, and when I tried to uninstall and then download again, an error occurred.

**To Reproduce**

PS C:\Users\J22011> npm install -g @microsoft/inshellisense

#
# Fatal error in , line 0
# Fatal process out of memory: Zone
#
#
#
#FailureMessage Object: 00000020147F5C70
 1: 00007FF6120B433F
 2: 00007FF611FB61DF
 3: 00007FF612E82282
 4: 00007FF612A83D83
 5: 00007FF612566654
 6: 00007FF612FBD72D
 7: 00007FF612FBD84E
 8: 00007FF612F4AF82
 9: 00007FF612F46C0A
10: 00007FF612F42D5A
11: 00007FF6129F2441
12: 00007FF6129BF361
13: 00007FF611FB8C3D
14: 00007FF612106CCD
15: 00007FF6132A4590
16: 00007FFCDF8F257D BaseThreadInitThunk+29
17: 00007FFCE01EAA58

**Expected behavior**

**Environment**
 - OS: [windows 11]
 - Output of `inshellisense --version`: current version 
 - Nodejs Version: [v20.9.0]

**Comment by cpendery** [comment]
Closing as bindings were removed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5) so this should no longer be an issue
