### ISSUE TITLE
Keybinding doesn't work

### ISSUE THREAD

**Issue by garysassano** [microsoft/inshellisense#89]
**Describe the bug**
I followed the Quickstart guide but couldn't get keybinding to work.

**To Reproduce**
1. Open WSL2 bash terminal in VS Code
2. Execute `npm install -g @microsoft/inshellisense`
3. Start typing a command, then press `CTRL+a`
4. The cursor moves to the beginning of the line.

**Expected behavior**
I expected to get inshellisense prompts.

**Environment**
 - OS: WSL2 Ubuntu 22.04 LTS on Windows 11 23H2
 - Output of `inshellisense --version`: 0.0.1-rc.4
 - Nodejs Version: v18.18.2

**Additional context**

**Comment by theKnightsOfRohan** [comment]
Did you run `inshellisense bind` before pressing `CTRL+a`?

**Comment by garysassano** [comment]
The issue got fixed after restarting the system.
