### ISSUE TITLE
List of command line tools

### ISSUE THREAD

**Issue by umol-unibas** [microsoft/inshellisense#96]
As i can not find a discussion board I'll give it a try and post my question / request here...

**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
Would be great to have a list of all command line tools implemented in inshellisense. So contributors can check if there is a cmd-tool lacking and users can decide if inshellisense is usefull to them - thanks

**Describe alternatives you've considered**
none

**Additional context**
Great tool - thanks ;)

**Comment by theKnightsOfRohan** [comment]
All of the specs included are listed at https://github.com/withfig/autocomplete , which is the completion agent this repo uses for its specs. All of the specs which this repo uses are created and stored in that repo.

**Comment by umol-unibas** [comment]
Cool, thanks! 👍🏼
